version: 1.0.{build}

install:
- dir c:\go16
# download bunch of files in a row using PS
#- ps: Start-FileDownload 'https://dl.dropboxusercontent.com/s/c1by0uulee6g8th/wxWidgets.7z?dl=0' -FileName wxWidgets.7z
#- ps: Start-FileDownload 'https://drive.google.com/uc?export=download&id=0B-98fOyaZKJ5YWVnb29JZXFQWkU' -FileName llvmlibs.7z
#- ps: Start-FileDownload 'https://drive.google.com/uc?export=download&id=0B8A6NaxhQAGRa21fbDQteTN1dGs' -FileName vulkan.7z
#- ps: Start-FileDownload 'https://drive.google.com/uc?export=download&id=0B6v_qtb9hkicQ2hHa2dRbF83cE0' -FileName zlib.7z
- ps: Start-FileDownload https://www.appveyor.com/downloads/Appveyor.NUnitLogger.zip
- ps: Start-FileDownload https://www.appveyor.com/downloads/Appveyor.NUnit3Logger.zip

# download bunch of files in a row using appveyor.exe
- appveyor DownloadFile "https://dl.dropboxusercontent.com/s/c1by0uulee6g8th/wxWidgets.7z?dl=0" -FileName wxWidgets.7z
- appveyor DownloadFile "https://drive.google.com/uc?export=download&id=0B-98fOyaZKJ5YWVnb29JZXFQWkU" -FileName llvmlibs.7z
- appveyor DownloadFile "https://drive.google.com/uc?export=download&id=0B8A6NaxhQAGRa21fbDQteTN1dGs" -FileName vulkan.7z
- appveyor DownloadFile "https://drive.google.com/uc?export=download&id=0B6v_qtb9hkicQ2hHa2dRbF83cE0" -FileName zlib.7z

- appveyor PushArtifact README.md -Verbosity Quiet
- ps: Push-AppveyorArtifact C:\go16\CONTRIBUTORS -Verbosity Normal
- ps: Push-AppveyorArtifact C:\go16\AUTHORS -Verbosity Minimal
- ps: Push-AppveyorArtifact C:\go16\LICENSE -Verbosity Quiet

build: off

test_script:
- echo Zipping for upload through 'artifacts' section
- 7z a go17.zip c:\go17
- copy go17.zip go17-1.zip
- appveyor PushArtifact go17-1.zip -Type Auto -Verbosity Minimal
- copy go17.zip go17-2.zip
- ps: Push-AppveyorArtifact go17-1.zip
- ps: Start-FileDownload https://nodejs.org/dist/v6.5.0/node-v6.5.0-darwin-x64.tar.gz -FileName "$env:appveyor_build_folder\node-v6.5.0.zip" -Timeout 1000
- appveyor DownloadFile https://nodejs.org/dist/v6.6.0/node-v6.6.0-darwin-x64.tar.gz -Timeout 1000
- mklink go17-1-link.zip go17-1.zip
- ps: Push-AppveyorArtifact go17-1-link.zip
- mklink go17-2-link.zip go17-1.zip
- move C:\go16 %appveyor_build_folder%\go16
- appveyor PushArtifact README.md -FileName README-2.md -Verbosity Normal

artifacts:
- path: go17.zip
- path: go17-2-link.zip
- path: go16

on_failure:
- ps: Get-EventLog AppVeyor -newest 10 | Format-List
